version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
      #docker_layer_caching: true
    resource_class: large
    steps:
      - checkout
      - run: |
          sudo apt-get install -y docker-buildx-plugin
      - run: |
          echo "$GITHUB_ACCESS_KEY" | docker login -u seungjin --password-stdin ghcr.io
      - run: |
          docker build -f Fedora/43/Containerfile \
          -t ghcr.io/seungjin/toolbox:fedora-43 ./Fedora/43/
          docker push ghcr.io/seungjin/toolbox:fedora-43
      - run: |
          docker build -f Fedora/42/Containerfile \
          -t ghcr.io/seungjin/toolbox:fedora-42 ./Fedora/42/
          docker push ghcr.io/seungjin/toolbox:fedora-42
      - run: |
          docker build -f Fedora/rawhide/Containerfile \
          -t ghcr.io/seungjin/toolbox:fedora-rawhide ./Fedora/rawhide/
          docker push ghcr.io/seungjin/toolbox:fedora-rawhide
      - run: |
          docker build -f Debian/13/Containerfile \
          -t ghcr.io/seungjin/toolbox:debian-13 ./Debian/13/
          docker push ghcr.io/seungjin/toolbox:debian-13  
      - run: |
          docker build -f Debian/12/Containerfile \
          -t ghcr.io/seungjin/toolbox:debian-12 ./Debian/12/
          docker push ghcr.io/seungjin/toolbox:debian-12          
      - run: |
          docker build -f Debian/unstable/Containerfile \
          -t ghcr.io/seungjin/toolbox:debian-unstable ./Debian/unstable/
          docker push ghcr.io/seungjin/toolbox:debian-unstable          
      - run: |
          docker build -f DevContainer/Containerfile.debian \
          -t ghcr.io/seungjin/codespace:debian ./DevContainer/
          docker push ghcr.io/seungjin/codespace:debian
      #- run: |
      #    docker build -f Debian-guix/Containerfile \
      #    -t ghcr.io/seungjin/debian-guix:latest ./Debian-guix/
      #    docker push ghcr.io/seungjin/debian-guix:latest
      #- run: |
      #    docker build -f Alpine-guix/Containerfile \
      #    -t ghcr.io/seungjin/alpine-guix:latest ./Alpine-guix/
      #    docker push ghcr.io/seungjin/alpine-guix:latest
      #- run: |
      #    docker buildx imagetools create \
      #    -t ghcr.io/seungjin/toolbox:latest \
      #    ghcr.io/seungjin/toolbox:<<pipeline.parameters.image-tag>>

workflows:
  commit:
    jobs:
      - build
  daily:
    triggers:
      - schedule:
          cron: "30 18 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build

